/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.republica.view.moradores;

import javax.swing.JButton;


/**
 *
 * @author bruno
 */
public class ListaMoradoresView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManterMoradores
     */
    public ListaMoradoresView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMoradores = new javax.swing.JTable();
        btnRemover = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnHistorico = new javax.swing.JButton();
        btnConvidar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Manter Moradores da República");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableMoradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Data de Ingresso", "Rateio %"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMoradores.setRowHeight(25);
        jScrollPane1.setViewportView(tableMoradores);
        if (tableMoradores.getColumnModel().getColumnCount() > 0) {
            tableMoradores.getColumnModel().getColumn(0).setPreferredWidth(200);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 461, 130));

        btnRemover.setText("Remover da República");
        getContentPane().add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 220, 70, -1));

        btnHistorico.setText("Ver Histórico");
        getContentPane().add(btnHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        btnConvidar.setText("Convidar Morador / Sem Teto");
        btnConvidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvidarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConvidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvidarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConvidarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

    }//GEN-LAST:event_btnEditarActionPerformed

    //Métodos inseridos manualmente
    
    public JButton getBtnEditar() {
        return btnEditar;
    }

    public void setBtnEditar(JButton btnEditar) {
        this.btnEditar = btnEditar;
    }

    public JButton getBtnConvidar() {
        return btnConvidar;
    }

    public void setBtnConvidar(JButton btnConvidar) {
        this.btnConvidar = btnConvidar;
    }

    public JButton getBtnHistorico() {
        return btnHistorico;
    }

    public void setBtnHistorico(JButton btnHistorico) {
        this.btnHistorico = btnHistorico;
    }

    public JButton getBtnRemover() {
        return btnRemover;
    }

    public void setBtnRemover(JButton btnRemover) {
        this.btnRemover = btnRemover;
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvidar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnHistorico;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMoradores;
    // End of variables declaration//GEN-END:variables
}
